feat: add new challenge
morpho-labs/hack-smart-contracts pull request #10
Opened 2023-05-16 14:50 UTC by Tristan22400

Add update proxy challenge

2023-05-18 08:03 UTC, MerlinEgalite requested changes

2023-05-18 08:03 UTC, MerlinEgalite commented on src/ProxyDeploiment.sol
deployment for the name of the contract

2023-05-18 08:03 UTC, MerlinEgalite commented on src/ProxyDeploiment.sol
> +
space can be removed

2023-05-18 08:03 UTC, MerlinEgalite commented on src/ProxyDeploiment.sol
> +     * @dev Delegates the current call to `implementation`.
NATSPECs can be cleaned

2023-05-22 11:49 UTC, MerlinEgalite requested changes

2023-05-22 13:22 UTC, MerlinEgalite approved these changes

2023-05-22 15:34 UTC, makcandrov commented
Perhaps we can use `ERC20` and `Ownable` from OZ also here

2023-05-23 07:55 UTC, Tristan22400 commented
> Perhaps we can use `ERC20` and `Ownable` from OZ also here

I think it add some complexity on top of the code which is not necessary.

2023-05-24 09:40 UTC, Tristan22400 commented
What do you think @makcandrov ?

2023-05-24 13:18 UTC, merged