fix: add oracle manipulation
morpho-labs/hack-smart-contracts pull request #12
Opened 2023-05-17 15:33 UTC by Tristan22400

2023-05-22 15:33 UTC, makcandrov commented on src/oracle-manipulation/oracle.sol
> +contract ERC20 {
Why Solmate over OZ? imo OZ would be more adapted as it is better known, and easier to read

2023-05-22 15:41 UTC, makcandrov commented on src/oracle-manipulation/oracle.sol
> +contract ERC20 {
Also `ERC20` from OZ is not marked as abstract, so we would no more need `ERC20Real`

2023-05-22 16:07 UTC, MerlinEgalite commented on src/oracle-manipulation/oracle.sol
> +contract ERC20 {
You can just import `ERC20Mock` from the `test` folder. Tbh i don't care. Juste the more we reuse code the faster

2023-05-22 20:04 UTC, makcandrov requested changes

2023-05-23 08:55 UTC, Tristan22400 commented on src/oracle-manipulation/oracle.sol
> +contract ERC20 {
In both case, we need to deploy a new contract to mint some tokens that can be added to the Linear Pool. So It is fine like that in my opinion.

2023-05-24 09:39 UTC, Tristan22400 commented
I proposed to close this PR to just keep the ones you open @makcandrov.

2023-05-24 12:26 UTC, makcandrov commented
yep closing it in favor of #15

2023-05-24 12:26 UTC, closed without merging