fix: spelling in the exercise
morpho-labs/hack-smart-contracts pull request #3
Opened 2023-05-15 14:23 UTC by Tristan22400

Fix: https://github.com/morpho-labs/hack-smart-contracts/issues/1

2023-05-15 14:43 UTC, makcandrov commented
Exercice => Exercise (everywhere)

2023-05-15 15:30 UTC, makcandrov requested changes

2023-05-15 15:30 UTC, makcandrov commented on src/Hack.sol
>      function withrawETH() external onlyOwner {
```suggestion
    /// @dev Withdraws all the ethers to owner's address.
    function withdrawETH() external onlyOwner {
```

2023-05-15 15:30 UTC, makcandrov commented on src/Hack.sol
>      function setRewardsAtRoundfor(uint256 _roundIndex, address[] calldata _recipients) external onlyOwner {
```suggestion
    function setRewardsAtRoundFor(uint256 _roundIndex, address[] calldata _recipients) external onlyOwner {
```

2023-05-15 15:30 UTC, makcandrov commented on src/Hack.sol
> +    /// @param _recipient The address whose authorisation is to be checked.
```suggestion
    /// @dev Checks if an address can participate in this round.
    /// @param _roundIndex The index of the round to be checked.
    /// @param _recipient The address whose authorization is to be checked.
```

2023-05-15 16:32 UTC, MerlinEgalite approved these changes

2023-05-15 16:32 UTC, MerlinEgalite commented on src/Hack.sol
> +/// Exercise 1 ///
```suggestion
/* Exercise 1 */
```

and everywhere else

2023-05-16 08:04 UTC, MerlinEgalite approved these changes

2023-05-16 08:07 UTC, makcandrov commented on src/Hack.sol
> +    /// @dev Withdraws all of the money from one's coffer slot.
```suggestion
    /// @dev Withdraws all the money from one's coffer slot.
```

2023-05-16 08:07 UTC, makcandrov commented on src/Hack.sol
>      /// @dev Deposits money in one's coffer slot.
```suggestion
    /// @dev Deposits money into one's coffer slot.
```

2023-05-16 08:07 UTC, makcandrov commented on src/Hack.sol
>      /// @param _owner The coffer to deposit money on.
```suggestion
    /// @param _owner The owner of the coffer.
```

2023-05-16 08:07 UTC, makcandrov commented on src/Hack.sol
> +    /// @param _slot The slot to deposit money on.
```suggestion
    /// @param _slot The slot to deposit money into.
```

2023-05-16 12:12 UTC, makcandrov approved these changes

2023-05-16 12:43 UTC, merged