fix: remove reentrancy in ex13
morpho-labs/hack-smart-contracts pull request #8
Opened 2023-05-16 12:27 UTC by Tristan22400

2023-05-16 13:58 UTC, makcandrov commented
I think a re-entrancy is still possible here

2023-05-16 14:10 UTC, makcandrov commented
I'd have fixed it like that

```
function distribute(uint256 _count) public {
        require(currentStage == Stage.WinnersFound, "Winners must have been found");
        while (
            cursorDistribute < winners.length
            && _count != 0
        ) {
            // Send ether to the winners. Do not block if one of the account cannot receive ETH.
            winners[cursorDistribute++].call{value: totalBalance / (winners.length - numberOfLosers)}("");
            _count--;
        }
        if (cursorDistribute == winners.length - 1) currentStage = Stage.Distributed;
    }
```

though I don't know how to get rid of the warning

2023-05-16 15:37 UTC, Tristan22400 commented
> I think a re-entrancy is still possible here

Can you explain it? I do not see how it is possible.

2023-05-16 15:46 UTC, Tristan22400 commented
> I'd have fixed it like that
> 
> ```
> function distribute(uint256 _count) public {
>         require(currentStage == Stage.WinnersFound, "Winners must have been found");
>         while (
>             cursorDistribute < winners.length
>             && _count != 0
>         ) {
>             // Send ether to the winners. Do not block if one of the account cannot receive ETH.
>             winners[cursorDistribute++].call{value: totalBalance / (winners.length - numberOfLosers)}("");
>             _count--;
>         }
>         if (cursorDistribute == winners.length - 1) currentStage = Stage.Distributed;
>     }
> ```
> 
> though I don't know how to get rid of the warning

I agree with you. I do not know how to resolve it.

2023-05-17 13:33 UTC, MerlinEgalite requested changes

2023-05-17 13:33 UTC, MerlinEgalite commented on src/Hack.sol
>          // Update the cursor in case we haven't finished going through the list.
to remove no?

2023-05-17 13:33 UTC, MerlinEgalite commented on src/Hack.sol
> +            winners[cursorDistribute++].call{value: totalBalance / (winners.length - numberOfLosers)}("");
that's not ideal in term of storage writing, could be better if `cursorDistribute` is stored in a temp variable?

2023-05-17 19:12 UTC, MerlinEgalite commented on src/Hack.sol
> +            winners[cursorDistribute++].call{value: totalBalance / (winners.length - numberOfLosers)}("");
ok haha let's go

2023-05-17 19:12 UTC, MerlinEgalite approved these changes

2023-05-19 07:21 UTC, merged